### ISSUE TITLE
unable to test

### ISSUE THREAD

**Issue by oriSomething** [levanto-financial/ember-lodash#14]
when i try to do that in the browser, i get this errors:
<img width="1419" alt="screen shot 2016-01-13 at 16 31 21" src="https://cloud.githubusercontent.com/assets/2685242/12296924/44d5776e-ba13-11e5-836d-f88ec70a2d0a.png">

from command line i just get stuck and when i terminate i get this:
```
    ---
        message: >
            Received SIGINT signal
```

tried in:
- node v4.2.2/v5.3.0
- npm v2.14.10 / v3.5.2
- ember-cli 1.13.12

**Comment by tchak** [comment]
This looks like a problem with old ember build and jQuery. This problem was fixed on all recent and LTS versions of ember as far as I know. Reopen if still an issue please.
